#!/usr/bin/env bash
# audit_cluster.sh — produce a read-only inventory of the cluster state
# of the turbomole-cosmo repo and write it to docs/audit/cluster-<date>.md.
#
# Run on the cluster login node (Wice tier-2 VSC) from inside the repo:
#
#     cd $VSC_DATA/turbomole-cosmo
#     scripts/audit_cluster.sh
#
# Then commit the generated report so the GitHub repo has a record of
# the cluster state at the time of the audit:
#
#     git add docs/audit/cluster-*.md
#     git commit -m 'docs: cluster audit YYYY-MM-DD'
#     git push
#
# The script is strictly READ-ONLY on every file outside the report it
# produces. It never modifies, renames, or deletes anything.
#
# Sections produced:
#   1. Quota & top-level disk usage
#   2. Per-molecule breakdown (size, root files, per-protocol status)
#   3. Compute artifacts > 1 GB
#   4. Failed / abandoned protocol working dirs
#   5. SLURM logs (recent stdout/stderr files)
#   6. Archive directories
#   7. Anomalies & recommendations
# -----------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"
DATE="$(date +%Y-%m-%d)"
REPORT_DIR="$REPO_ROOT/docs/audit"
REPORT="$REPORT_DIR/cluster-${DATE}.md"
mkdir -p "$REPORT_DIR"

# ----- helpers ---------------------------------------------------------------

# Print to the report.
out()  { printf '%s\n' "$*" >> "$REPORT"; }
hdr()  { printf '\n## %s\n\n' "$*" >> "$REPORT"; }
code() { printf '```\n' >> "$REPORT"; }

# Pretty file size for one file in human units (or "-" if missing).
fsize() {
  if [[ -f "$1" ]]; then
    du -h "$1" 2>/dev/null | awk '{print $1}'
  else
    printf -- "-"
  fi
}

# Recursive size for a dir in human units (or "-" if missing).
dsize() {
  if [[ -d "$1" ]]; then
    du -sh "$1" 2>/dev/null | awk '{print $1}'
  else
    printf -- "-"
  fi
}

# Yes/no helper for existence.
ynfile() { [[ -f "$1" ]] && printf "YES" || printf "no"; }

# ----- header ----------------------------------------------------------------

: > "$REPORT"   # truncate
out "# Cluster Inventory — $REPO_ROOT"
out ""
out "**Date:** $DATE"
out "**Host:** $(hostname)"
out "**User:** $USER"
out "**Generated by:** scripts/audit_cluster.sh"
out ""
out "This report is read-only and committed to git as the durable record"
out "of the cluster state at the time of the audit. Compute artifacts"
out "themselves (mos files, .cosmo, ridft.out) are NOT pushed to git —"
out "only their summary inventory is."

# ----- section 1: quotas + top-level usage -----------------------------------

hdr "1. Quota & top-level disk usage"
code
echo "REPO_ROOT: $REPO_ROOT" >> "$REPORT"
echo "Total repo size: $(dsize "$REPO_ROOT")" >> "$REPORT"
echo "" >> "$REPORT"
echo "Top-level subdirectories (sorted by size):" >> "$REPORT"
du -sh "$REPO_ROOT"/* 2>/dev/null | sort -hr >> "$REPORT" || true
echo "" >> "$REPORT"

if command -v mmlsquota >/dev/null 2>&1; then
  echo "GPFS quota (mmlsquota):" >> "$REPORT"
  mmlsquota 2>&1 | head -20 >> "$REPORT" || true
elif [[ -n "${VSC_DATA:-}" ]]; then
  echo "VSC_DATA quota approximation:" >> "$REPORT"
  echo "  VSC_DATA=$VSC_DATA" >> "$REPORT"
  echo "  size:   $(dsize "$VSC_DATA")" >> "$REPORT"
fi
code

# ----- section 2: per-molecule breakdown -------------------------------------

hdr "2. Per-molecule breakdown"

if [[ ! -d "$REPO_ROOT/molecules" ]]; then
  out "(no molecules/ directory found)"
else
  for mol_dir in "$REPO_ROOT"/molecules/*/; do
    [[ -d "$mol_dir" ]] || continue
    mol="$(basename "$mol_dir")"
    out "### $mol"
    out ""
    out "- Total size: \`$(dsize "$mol_dir")\`"

    # Active geometry + charge
    xyz="$mol_dir/$mol.xyz"
    chg="$mol_dir/charge.txt"
    if [[ -f "$xyz" ]]; then
      n_atoms="$(head -n 1 "$xyz" | tr -d '[:space:]')"
      out "- Active geometry: \`$mol.xyz\` ($n_atoms atoms, $(fsize "$xyz"))"
    else
      out "- Active geometry: **missing** ($mol.xyz)"
    fi
    if [[ -f "$chg" ]]; then
      out "- Charge: \`$(cat "$chg" | tr -d '[:space:]')\`"
    else
      out "- Charge: **missing** (charge.txt)"
    fi

    out ""
    out "- Files at molecule root:"
    code
    ls -la "$mol_dir" 2>/dev/null | awk '!/^d/ && !/^total/ {print}' >> "$REPORT" || true
    code
    out ""

    # Per protocol working dir
    out "- Protocol working dirs:"
    code
    printf "%-28s %-8s %-7s %-7s %-12s %s\n" "DIR" "SIZE" "COSMO" "STAMP" "MOS" "RIDFT_STATUS" >> "$REPORT"
    for sub in "$mol_dir"/*/; do
      [[ -d "$sub" ]] || continue
      subname="$(basename "$sub")"
      # Skip the propka/ work dir and _archive-* (handled later)
      [[ "$subname" == "propka" ]] && continue
      [[ "$subname" == _archive* ]] && continue
      sz="$(dsize "$sub")"
      cosmo="$(find "$sub" -maxdepth 1 -name '*.cosmo' 2>/dev/null | head -1)"
      stamp="$(find "$sub" -maxdepth 1 -name '*_ok*.stamp' 2>/dev/null | head -1)"
      mos="$sub/mos"
      mos_size="$(fsize "$mos")"
      ridft="$sub/ridft.out"
      if [[ -f "$ridft" ]]; then
        rstat="$(grep -E 'ridft did not converge|ridft : all done|ATTENTION' "$ridft" 2>/dev/null | tail -1 | tr -s ' ' | cut -c1-40)"
        [[ -z "$rstat" ]] && rstat="(running or pre-SCF)"
      else
        rstat="-"
      fi
      printf "%-28s %-8s %-7s %-7s %-12s %s\n" \
        "$subname" "$sz" \
        "$([[ -n "$cosmo" ]] && echo YES || echo no)" \
        "$([[ -n "$stamp" ]] && echo YES || echo no)" \
        "$mos_size" "$rstat" >> "$REPORT"
    done
    code

    # propka subdir summary if present
    if [[ -d "$mol_dir/propka" ]]; then
      out ""
      out "- PROPKA workdir:"
      code
      ls -la "$mol_dir/propka" 2>/dev/null | awk '!/^d/ && !/^total/ {print}' >> "$REPORT" || true
      code
    fi
    out ""
  done
fi

# ----- section 3: files > 1 GB -----------------------------------------------

hdr "3. Compute artifacts > 1 GB"
code
echo "(find $REPO_ROOT -type f -size +1G -printf '%s %TY-%Tm-%Td %p\n' | sort -nr)" >> "$REPORT"
echo "" >> "$REPORT"
find "$REPO_ROOT" -type f -size +1G -printf '%s %TY-%Tm-%Td %p\n' 2>/dev/null \
  | sort -nr | awk '{ printf "%7.2f GB  %s  %s\n", $1/1024/1024/1024, $2, $3 }' \
  >> "$REPORT" || true
code

# ----- section 4: failed/abandoned protocol dirs -----------------------------

hdr "4. Failed / abandoned protocol working dirs"
out ""
out "Criteria: protocol working dir under \`molecules/<mol>/\` that has"
out "NO .cosmo file AND NO success stamp. These are candidates for"
out "deletion under the aggressive cleanup policy."
out ""
code
printf "%-12s %-22s %-8s %-12s %s\n" "MOLECULE" "PROTOCOL" "SIZE" "LAST_MTIME" "MOS_SIZE" >> "$REPORT"
for mol_dir in "$REPO_ROOT"/molecules/*/; do
  [[ -d "$mol_dir" ]] || continue
  mol="$(basename "$mol_dir")"
  for sub in "$mol_dir"/*/; do
    [[ -d "$sub" ]] || continue
    subname="$(basename "$sub")"
    [[ "$subname" == "propka" ]] && continue
    [[ "$subname" == _archive* ]] && continue
    cosmo="$(find "$sub" -maxdepth 1 -name '*.cosmo' 2>/dev/null | head -1)"
    stamp="$(find "$sub" -maxdepth 1 -name '*_ok*.stamp' 2>/dev/null | head -1)"
    if [[ -z "$cosmo" && -z "$stamp" ]]; then
      sz="$(dsize "$sub")"
      mtime="$(stat -c '%y' "$sub" 2>/dev/null | cut -c1-19)"
      mos_size="$(fsize "$sub/mos")"
      printf "%-12s %-22s %-8s %-12s %s\n" "$mol" "$subname" "$sz" "${mtime%% *}" "$mos_size" >> "$REPORT"
    fi
  done
done
code

# ----- section 5: SLURM logs -------------------------------------------------

hdr "5. SLURM stdout/stderr logs"
out ""
out "Recent SLURM logs across all molecule trees (oldest first by mtime,"
out "to identify forensic-only stragglers)."
out ""
code
find "$REPO_ROOT" -type f \
     \( -name 'slurm-*.out' -o -name 'slurm-*.err' \
        -o -name 'xtb-preopt*.out' -o -name 'xtb-preopt*.err' \
        -o -name 'scf-cosmo.out' -o -name 'scf-cosmo.err' \
        -o -name 'prep-cosmo.out' -o -name 'prep-cosmo.err' \) \
     -printf '%TY-%Tm-%Td %TH:%TM  %8s  %p\n' 2>/dev/null \
  | sort >> "$REPORT" || true
code

# ----- section 6: archive directories ---------------------------------------

hdr "6. Archive directories"
out ""
out "Contents of any \`_archive-*\` subdirs (forensic record of prior"
out "failed attempts). Under the aggressive policy, archives older than"
out "30 days are candidates for deletion."
out ""
code
ARCH_LIST="$(find "$REPO_ROOT" -type d -name '_archive-*' 2>/dev/null | sort)"
if [[ -z "$ARCH_LIST" ]]; then
  echo "(no _archive-* directories found)" >> "$REPORT"
else
  while IFS= read -r d; do
    [[ -d "$d" ]] || continue
    sz="$(dsize "$d")"
    mtime="$(stat -c '%y' "$d" 2>/dev/null | cut -c1-19)"
    printf "  %-8s %-19s %s\n" "$sz" "$mtime" "$d" >> "$REPORT"
  done <<< "$ARCH_LIST"
fi
code

# ----- section 7: anomalies + recommendations -------------------------------

hdr "7. Anomalies & recommendations"
out ""
out "Auto-flagged items the human auditor should review:"
out ""

# Detect any molecule with .xyz atom count != charge consistent
for mol_dir in "$REPO_ROOT"/molecules/*/; do
  mol="$(basename "$mol_dir")"
  xyz="$mol_dir/$mol.xyz"
  if [[ -f "$xyz" ]]; then
    n_atoms="$(head -n 1 "$xyz" | tr -d '[:space:]')"
    if ! [[ "$n_atoms" =~ ^[0-9]+$ ]]; then
      out "- ⚠️  \`molecules/$mol/$mol.xyz\` does not start with an atom count on line 1."
    fi
  fi
done

# Detect any working dir with no progress files (truly empty/abandoned)
for mol_dir in "$REPO_ROOT"/molecules/*/; do
  mol="$(basename "$mol_dir")"
  for sub in "$mol_dir"/*/; do
    [[ -d "$sub" ]] || continue
    subname="$(basename "$sub")"
    [[ "$subname" == "propka" ]] && continue
    [[ "$subname" == _archive* ]] && continue
    n_files="$(find "$sub" -maxdepth 2 -type f 2>/dev/null | wc -l)"
    if [[ "$n_files" -lt 3 ]]; then
      out "- ⚠️  \`molecules/$mol/$subname/\` contains $n_files file(s) — looks abandoned."
    fi
  done
done

# Cluster-only molecules that the Mac mirror probably doesn't have
for mol_dir in "$REPO_ROOT"/molecules/*/; do
  mol="$(basename "$mol_dir")"
  if [[ -d "$mol_dir/propka" ]]; then
    out "- 📋 \`molecules/$mol/propka/\` exists on cluster — Mac mirror is likely stale on this molecule."
  fi
done

out ""
out "## Done."
out ""
out "Report written to: \`$REPORT\`"
out "Next: \`git add docs/audit/cluster-${DATE}.md && git commit -m 'docs: cluster audit ${DATE}' && git push\`"

echo "Cluster inventory written to: $REPORT"
echo "Total report size: $(fsize "$REPORT")"
echo
echo "Next steps:"
echo "  git add docs/audit/cluster-${DATE}.md"
echo "  git commit -m 'docs: cluster audit ${DATE}'"
echo "  git push"
