#!/usr/bin/env python3
"""build_screen_input.py — generate ONE COSMOtherm solubility-screening input.

Screens all pure solvents AND every binary mixture in a single job, each
returning log10(x_RS) on one relative scale — replicating the COSMOthermX
desktop layout:

  * every solvent is listed with ALL its conformers (c0..cN), Comp-grouped and
    read in place from the COSMObase subdirectory via per-file fdir= ;
  * mixtures are appended as x={...} composition vectors (MOLE fractions) on the
    `solub screening ... pure=all liquid relative` line.

The compound order is the order of the solvent list; the solute is last, so
solute index = (#solvents + 1). Each x={...} vector is that long, with the
mixture's mole fractions at the component indices and 0 everywhere else
(solute component = 0).

Usage:
  build_screen_input.py --molecule M --solute-cosmo PATH --db-root DIR \
      --ctd CTD --cdir DIR --ldir DIR --solvents FILE --mixtures FILE
Writes the .inp to stdout; a one-line summary to stderr.
"""
from __future__ import annotations
import argparse
import os
import re
import sys


def read_solvents(path: str) -> list[str]:
    names = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            names.append(line.split()[0])
    return names


def read_mixtures(path: str):
    mixes = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            p = line.split()
            if len(p) < 5:
                continue
            mixes.append((p[0], p[1], p[2], p[3], p[4]))  # label s1 s2 x1 x2
    return mixes


_CONF_RE = re.compile(r'^(?P<name>.+)_c(?P<n>\d+)\.cosmo$')


def index_db(db_root: str) -> dict[str, list[tuple[int, str]]]:
    """Walk the COSMObase tree once; map solvent basename -> sorted [(conf, path)]."""
    db: dict[str, list[tuple[int, str]]] = {}
    for dirpath, _dirs, files in os.walk(db_root):
        for fn in files:
            m = _CONF_RE.match(fn)
            if not m:
                continue
            db.setdefault(m.group('name'), []).append(
                (int(m.group('n')), os.path.join(dirpath, fn)))
    for nm in db:
        db[nm].sort()
    return db


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--molecule', required=True)
    ap.add_argument('--solute-cosmo', required=True)
    ap.add_argument('--db-root', required=True)
    ap.add_argument('--ctd', required=True)
    ap.add_argument('--cdir', required=True)
    ap.add_argument('--ldir', required=True)
    ap.add_argument('--solvents', required=True)
    ap.add_argument('--mixtures', required=True)
    a = ap.parse_args()

    solvents = read_solvents(a.solvents)
    mixes = read_mixtures(a.mixtures)
    idx = {name: i + 1 for i, name in enumerate(solvents)}   # 1-based compound index
    n_solv = len(solvents)
    solute_idx = n_solv + 1
    n_comp = n_solv + 1

    db = index_db(a.db_root)

    out: list[str] = []
    out.append(f'ctd = {a.ctd} cdir = "{a.cdir}" ldir = "{a.ldir}"')
    out.append('notempty wtln')
    out.append('!! generated by turbomole-cosmo pipeline (multi-conformer screen) !!')

    # --- solvent compound blocks (all conformers, Comp-grouped) ---
    missing = []
    for name in solvents:
        confs = db.get(name, [])
        if not confs:
            missing.append(name)
            continue
        if len(confs) == 1:
            d = os.path.dirname(confs[0][1])
            b = os.path.basename(confs[0][1])
            out.append(f'f = "{b}" fdir="{d}" VPfile')
        else:
            last = len(confs) - 1
            for k, (_n, path) in enumerate(confs):
                d = os.path.dirname(path)
                b = os.path.basename(path)
                if k == 0:
                    out.append(f'f = "{b}" fdir="{d}" Comp = "{name}" [ VPfile')
                elif k == last:
                    out.append(f'f = "{b}" fdir="{d}" ]')
                else:
                    out.append(f'f = "{b}" fdir="{d}"')

    if missing:
        print(f"ERROR: no conformers found in COSMObase for: {', '.join(missing)}",
              file=sys.stderr)
        return 3

    # --- solute (last compound) ---
    sdir = os.path.dirname(os.path.abspath(a.solute_cosmo))
    sb = os.path.basename(a.solute_cosmo)
    out.append(f'f = "{sb}" fdir="{sdir}" VPfile')

    # --- mixtures -> x={...} mole-fraction vectors ---
    xvecs, labels = [], []
    for label, s1, s2, x1, x2 in mixes:
        if s1 not in idx or s2 not in idx:
            print(f"ERROR: mixture '{label}' component not in solvent list: {s1} / {s2}",
                  file=sys.stderr)
            return 3
        vec = ['0'] * n_comp
        vec[idx[s1] - 1] = x1
        vec[idx[s2] - 1] = x2
        xvecs.append('x={' + ' '.join(vec) + '}')
        labels.append(label)

    job = (f'tc=25.0 solub screening solute={solute_idx} pure=all liquid relative '
           + ' '.join(xvecs))
    out.append(job)
    out.append('# mixture x={} order: ' + ' '.join(labels))

    sys.stdout.write('\n'.join(out) + '\n')
    print(f"[build_screen_input] {n_solv} solvents (compound 1..{n_solv}), "
          f"solute='{a.molecule}' (compound {solute_idx}), {len(xvecs)} mixtures",
          file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
